import numpy as np
a=np.array([1,2,3])
print(a)
b=np.zeros((2,3))
print(b)
c=np.ones(5)
print(c)
d=np.arange(0,10,2)
print(d)
e=np.linspace(0,1,3)
print(e)
f=np.random.rand(2,2)
print(f)
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
